### ISSUE TITLE
Fix Bootstrap_Walker_Nav_Menu PHP Warning

### ISSUE THREAD

**Issue by cjg89** [UCF/Faculty-Relations-Theme#2]
PHP Warning:  Declaration of Bootstrap_Walker_Nav_Menu::start_lvl(&$output, $depth) should be compatible with Walker_Nav_Menu::start_lvl(&$output, $depth = 0, $args = Array) in functions/base.php on line 458

**Comment by jmbarne3** [comment]
Fixed by #5
