### ISSUE TITLE
Clean up PHP notices, deprecation messages

### ISSUE THREAD

**Issue by cjg89** [UCF/Faculty-Relations-Theme#3]
Make sure scripts and styles are enqueued properly, account for undefined array indexes, ensure referenced constants have been defined, etc.

See also:
PHP Deprecated:  Non-static method DOMDocument::loadHTML() should not be called statically in Faculty-Relations-Theme/shortcodes.php on line 24

**Comment by jmbarne3** [comment]
Fixed by #5
